### ISSUE TITLE
remove duplication in constructors

### ISSUE THREAD

**Issue by kwhinnery** [twilio/automated-survey-java#4]
in `SurveyService.java`, the default constructor and parameterized constructor are basically the same. The default constructor should use the parameterized constructor, given default arguments. 

``` java
public class Kevin {
  private boolean awesome;

  public Kevin() {
    this(true);
  }

  public Kevin(boolean awesome) {
    this.awesome = awesome;
  }
}
```

**Comment by kwhinnery** [comment]
This should be done for other constructors as well.

**Comment by kwhinnery** [comment]
(the reason being we want to keep the code [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself))

**Comment by brampersandon** [comment]
Absolutely! Done for each class in Models and Util (the controller is not instantiated).
